# Generated by Django 3.2.8 on 2021-10-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20211007_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
